### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by GaryHillis** [dpet23/Export-iTunes-Playlists#4]
I think this will work better if you use UTF-8-MAC encoding.

**Comment by dpet23** [comment]
The `ExportPlaylists.applescript` file is already saved using UTF-8 encoding.

I've tried running
```iconv -f UTF-8 -t UTF-8-MAC ./ExportPlaylists.applescript > ./ExportPlaylists_new.applescript```
but the files don't have any differences (according to Git).

Visual Studio Code with the AppleScript extension will incorrectly open the file using Mac Roman encoding, and some characters won't display correctly. However, reopening the file with UTF-8 encoding in VSCode will display all characters correctly.

**Comment by dpet23** [comment]
I'm not sure what changes are needed. If you have a suggestion, please reopen the issue or create a PR.
