### ISSUE TITLE
Error all_ps variable is not set ?

### ISSUE THREAD

**Issue by aarkkappler** [dpet23/Export-iTunes-Playlists#7]
Hello

i have this error

<img width="382" alt="Capture d’écran 2021-09-12 à 16 24 33" src="https://user-images.githubusercontent.com/9117901/132991619-3d23acad-60d9-4c8d-b488-5eae00a4a09c.png">

thank you

**Comment by dpet23** [comment]
This should be resolved in fdc2364. If the error persists, please reopen the issue.
